/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_samsung_dali_modelExporter_ModelExporter */

#ifndef _Included_com_samsung_dali_modelExporter_ModelExporter
#define _Included_com_samsung_dali_modelExporter_ModelExporter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_samsung_dali_modelExporter_ModelExporter
 * Method:    nativeExport
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_samsung_dali_modelExporter_ModelExporter_nativeExport
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_samsung_dali_modelExporter_ModelExporter
 * Method:    nativeGetErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_samsung_dali_modelExporter_ModelExporter_nativeGetErrorMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_samsung_dali_modelExporter_ModelExporter
 * Method:    nativeGetDliPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_samsung_dali_modelExporter_ModelExporter_nativeGetDliPath
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
