/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_samsung_dali_modelConverter_process_NativeExporter */

#ifndef _Included_com_samsung_dali_modelConverter_process_NativeExporter
#define _Included_com_samsung_dali_modelConverter_process_NativeExporter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_samsung_dali_modelConverter_process_NativeExporter
 * Method:    Export
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_samsung_dali_modelConverter_process_NativeExporter_Export
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_samsung_dali_modelConverter_process_NativeExporter
 * Method:    GetErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_samsung_dali_modelConverter_process_NativeExporter_GetErrorMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_samsung_dali_modelConverter_process_NativeExporter
 * Method:    GetDliPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_samsung_dali_modelConverter_process_NativeExporter_GetDliPath
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
